/* Generated by tools/circuits/sweep_nes001_audio.py --golden: ngspice run of
 * nes001_audio.cir (74HCU04 MOS pair), pulse pin, 47k TV input. Do not edit. */
#ifndef NES001_AUDIO_GOLDEN_H
#define NES001_AUDIO_GOLDEN_H
#define NES001_AUDIO_GOLDEN_HP_HZ 17.36f
#define NES001_AUDIO_GOLDEN_LP_HZ 17129.1f
#define NES001_AUDIO_GOLDEN_GAIN_DB 4.83f
#define NES001_AUDIO_GOLDEN_SUPPLY_GAIN_120HZ_DB 8.91f
static const float nes001_audio_golden_hz[] = {10.0f, 16.0f, 20.0f, 30.0f, 50.0f, 100.0f, 200.0f, 500.0f, 1000.0f, 2000.0f, 5000.0f, 8000.0f, 10000.0f, 12000.0f, 15000.0f, 20000.0f};
static const float nes001_audio_golden_db[] = {-6.245f, -3.380f, -2.408f, -1.214f, -0.464f, -0.109f, -0.016f, 0.007f, 0.000f, -0.044f, -0.343f, -0.849f, -1.267f, -1.729f, -2.465f, -3.718f};
#endif
