/* Generated by tools/circuits/sweep_nes001_video.py --golden: ngspice run of
 * nes001_video_chain.cir with rb=3300, cpk=2p. Do not edit. */
#ifndef NES001_VIDEO_GOLDEN_H
#define NES001_VIDEO_GOLDEN_H
#define NES001_GOLDEN_RISE_10_90_NS 107.5f
#define NES001_GOLDEN_FALL_90_10_NS 11.0f
#define NES001_GOLDEN_ONE_PIXEL_PEAK 1.010f
static const float nes001_golden_row_gain_rel_row1[4] = {1.0705f, 1.0000f, 0.8972f, 1.0531f};
static const float nes001_golden_row_phase_rel_row1_deg[4] = {5.79f, 0.00f, -4.02f, 3.94f};
static const float nes001_golden_row_luma_error[4] = {-0.0316f, -0.0739f, -0.1094f, -0.0206f};
#endif
