/* Generated by tools/circuits/sweep_nes001_psu.py --golden: ngspice run of
 * nes001_psu.cir (NES-002 adaptor, bridge, reservoir, 7805 with dropout). Do not edit. */
#ifndef NES001_PSU_GOLDEN_H
#define NES001_PSU_GOLDEN_H
#define NES001_PSU_RIPPLE_K 2.41047e-03f       /* V_120 = k x I/(C x 10^(RR/20)) */
#define NES001_PSU_HARMONIC_2 0.3106f
#define NES001_PSU_HARMONIC_3 0.0829f
#define NES001_PSU_RAW_PP_K 0.6430f      /* raw_pp = k_raw x I/(2 f C) */
#define NES001_PSU_RAW_A 1.1572f
#define NES001_PSU_RAW_B -0.1157f
#define NES001_PSU_RAW_C 1.6114f
#define NES001_PSU_DROPOUT_V 7.0f
#define NES001_PSU_DROPOUT_Q 1.6310f
#define NES001_PSU_VIDEO_JACK_15734HZ_UV 78.2f
#define NES001_PSU_VIDEO_JACK_60HZ_UV 2.7f
/* c_res_uf, i_load_a, rr_db, vac, five_120hz_mv */
static const float nes001_psu_golden_rows[][5] = {
    {1000.0f, 0.4f, 62.0f, 10.0f, 0.80821f},
    {1000.0f, 0.4f, 73.0f, 10.0f, 0.22780f},
    {1000.0f, 0.6f, 62.0f, 10.0f, 1.13022f},
    {1000.0f, 0.6f, 73.0f, 10.0f, 0.31856f},
    {1000.0f, 0.8f, 62.0f, 10.0f, 15.33830f},
    {1000.0f, 0.8f, 73.0f, 10.0f, 14.82399f},
    {2200.0f, 0.4f, 62.0f, 10.0f, 0.37278f},
    {2200.0f, 0.4f, 73.0f, 10.0f, 0.10507f},
    {2200.0f, 0.6f, 62.0f, 10.0f, 0.52457f},
    {2200.0f, 0.6f, 73.0f, 10.0f, 0.14785f},
    {2200.0f, 0.8f, 62.0f, 10.0f, 0.66773f},
    {2200.0f, 0.8f, 73.0f, 10.0f, 0.18820f},
    {4700.0f, 0.4f, 62.0f, 10.0f, 0.17524f},
    {4700.0f, 0.4f, 73.0f, 10.0f, 0.04939f},
    {4700.0f, 0.6f, 62.0f, 10.0f, 0.24691f},
    {4700.0f, 0.6f, 73.0f, 10.0f, 0.06959f},
    {4700.0f, 0.8f, 62.0f, 10.0f, 0.31476f},
    {4700.0f, 0.8f, 73.0f, 10.0f, 0.08871f},
    {2200.0f, 0.6f, 73.0f, 8.0f, 195.83688f},
    {2200.0f, 0.6f, 73.0f, 8.5f, 0.14504f},
    {2200.0f, 0.6f, 73.0f, 9.0f, 0.14606f},
    {2200.0f, 0.6f, 73.0f, 9.5f, 0.14699f},
    {2200.0f, 0.6f, 73.0f, 10.0f, 0.14785f},
    {2200.0f, 0.6f, 73.0f, 11.0f, 0.14936f},
};
#endif
