/* Generated by tools/circuits/sweep_nes001_audio.py --golden: ngspice run of
 * nes001_audio.cir, pulse pin, a_ol=20, r_out=1k, r_tv=47k. Do not edit. */
#ifndef NES001_AUDIO_GOLDEN_H
#define NES001_AUDIO_GOLDEN_H
#define NES001_AUDIO_GOLDEN_HP_HZ 16.81f
#define NES001_AUDIO_GOLDEN_LP_HZ 15562.1f
static const float nes001_audio_golden_hz[] = {10.0f, 16.0f, 20.0f, 30.0f, 50.0f, 100.0f, 200.0f, 500.0f, 1000.0f, 2000.0f, 5000.0f, 8000.0f, 10000.0f, 12000.0f, 15000.0f, 20000.0f};
static const float nes001_audio_golden_db[] = {-6.032f, -3.230f, -2.289f, -1.144f, -0.433f, -0.098f, -0.011f, 0.010f, 0.000f, -0.053f, -0.411f, -1.007f, -1.491f, -2.018f, -2.844f, -4.218f};
#endif
