#!/usr/bin/env python3
"""Generate the empirical FW900 spatial/tonal coefficients from NIDL data.

Gaussian spot equivalents fit contrast modulation, not a complete measured MTF.
Horizontal video is sample-and-hold; vertical scanlines are impulses.
"""
import argparse
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def modulation(sigma, held):
    def response(x):
        if held:
            return sum(.5 * (math.erf((x-2*k+.5)/(math.sqrt(2)*sigma)) -
                             math.erf((x-2*k-.5)/(math.sqrt(2)*sigma))) for k in range(-12,13))
        return sum(math.exp(-.5*((x-2*k)/sigma)**2) for k in range(-12,13))
    peak, valley = response(0), response(1)
    return (peak-valley)/(peak+valley)


def sigma_for(cm, held):
    lo, hi = .05, 2.0
    for _ in range(70):
        mid = (lo+hi)/2
        if modulation(mid, held) > cm:
            lo = mid
        else:
            hi = mid
    return (lo+hi)/2


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = json.loads(Path(__file__).with_name('fw900_nidl.json').read_text())
    gray = data['grayscale']
    assert [x['input'] for x in gray] == list(range(256))
    levels = [x['luminance_fl'] for x in gray]
    assert all(a < b for a,b in zip(levels,levels[1:]))
    lut = [(v-levels[0])/(levels[-1]-levels[0]) for v in levels]
    arrays = {'fw900_tone': lut,
              'fw900_sigma_x': [sigma_for(cm, True) for row in data['vertical_grille_cm'] for cm in row],
              'fw900_sigma_y': [sigma_for(cm, False) for row in data['horizontal_grille_cm'] for cm in row],
              'fw900_uniformity': [v/data['white_luminance_fl'][1][1] for row in data['white_luminance_fl'] for v in row]}
    lines = ['// Generated by tools/measurements/build_fw900_model.py; do not edit.',
             '// Source and qualifications: tools/measurements/fw900_nidl.json.']
    for name, values in arrays.items():
        lines.append(f'const float {name}[{len(values)}]=float[{len(values)}](')
        lines.append(',\n'.join('    '+','.join(f'{v:.10f}' for v in values[i:i+8]) for i in range(0,len(values),8))+');')
    path = ROOT/'frontends/gpu/shaders/compute/fw900_data.glsl'
    result = '\n'.join(lines)+'\n'
    header = ROOT/'frontends/gpu/fw900_tone.h'
    c_result = '// Generated by tools/measurements/build_fw900_model.py.\n#ifndef FW900_TONE_H\n#define FW900_TONE_H\nstatic const float fw900_tone[256] = {\n' + ',\n'.join('    '+','.join(f'{v:.10f}f' for v in lut[i:i+8]) for i in range(0,256,8)) + '\n};\n#endif\n'
    if args.check:
        if header.read_text() != c_result:
            raise SystemExit('FW900 generated C data is stale')
        if path.read_text() != result:
            raise SystemExit('FW900 generated shader data is stale')
    else:
        path.write_text(result)
        header.write_text(c_result)
    print('FW900: 256 monotonic gray levels; 18 Gaussian equivalents; 9 luminance anchors')
    print('Centre sigma X/Y (1920x1200 raster pixels):', arrays['fw900_sigma_x'][4], arrays['fw900_sigma_y'][4])


if __name__ == '__main__':
    main()
