#!/usr/bin/env python3
"""NES-001 APU-to-jack audio response from the schematic.

Runs tools/circuits/nes001_audio.cir in ngspice over the 74HC04 gate's
open-loop gain and output resistance, the module follower's output resistance
and the TV's input resistance, for the pulse and the TND pin. Reports the
response relative to 1 kHz, the -3 dB corners, and writes a golden file for
the audio chain test (the rb=20/1k/100/47k case). Compare with rainwarrior's
hardware sweep: a single high-pass near 16 Hz on the NES (nesdev thread 17745).
"""
import argparse
import json
import math
from pathlib import Path
import re
import subprocess
import tempfile

import numpy as np

TEST_HZ = [10, 16, 20, 30, 50, 100, 200, 500, 1000, 2000, 5000, 8000, 10000, 12000, 15000, 20000]


def run(deck, params, work):
    deck = re.sub(r"^\.param .*$", ".param " + " ".join(f"{k}={v}" for k, v in params.items()), deck, flags=re.M)
    (work / "model.cir").write_text(deck)
    out = subprocess.run(["ngspice", "-b", "model.cir"], cwd=work, text=True,
                         stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if out.returncode != 0 or not (work / "ac.txt").exists():
        raise RuntimeError(out.stdout[-2000:])
    rows = [list(map(float, l.split())) for l in (work / "ac.txt").read_text().splitlines()[1:] if l.strip()]
    data = np.array(rows)
    return data[:, 0], data[:, 1], data[:, 2], data[:, 3]


def corners(f, db):
    """-3 dB points relative to 1 kHz, low and high, by interpolation."""
    ref = np.interp(1000.0, f, db)
    rel = db - ref
    lo = hi = None
    for i in range(1, len(f)):
        if f[i] <= 1000 and rel[i - 1] < -3 <= rel[i]:
            lo = f[i - 1] + (f[i] - f[i - 1]) * (-3 - rel[i - 1]) / (rel[i] - rel[i - 1])
        if f[i] > 1000 and rel[i - 1] >= -3 > rel[i] and hi is None:
            hi = f[i - 1] + (f[i] - f[i - 1]) * (rel[i - 1] + 3) / (rel[i - 1] - rel[i])
    return lo, hi, ref


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    parser.add_argument("--golden", type=Path)
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    deck = Path(__file__).with_name("nes001_audio.cir").read_text()
    results = []
    for src in (1, 2):
        for a_ol in (10, 20, 40):
            for r_out in (300, 1000, 2000):
                for r_tv in (10000, 47000, 1000000):
                    params = {"a_ol": a_ol, "r_out": r_out, "r_tv": r_tv, "r_follower": 100, "src": src}
                    with tempfile.TemporaryDirectory() as d:
                        f, jack_db, jack_ph, out_db = run(deck, params, Path(d))
                    lo, hi, ref = corners(f, jack_db)
                    lo_mb, hi_mb, ref_mb = corners(f, out_db)
                    r = {"src": "pulse" if src == 1 else "tnd", "a_ol": a_ol, "r_out": r_out, "r_tv": r_tv,
                         "gain_1khz_db": ref, "hp_hz": lo, "lp_hz": hi,
                         "motherboard_hp_hz": lo_mb, "motherboard_lp_hz": hi_mb,
                         "response_db": {str(h): float(np.interp(h, f, jack_db) - ref) for h in TEST_HZ}}
                    results.append(r)
                    print(f"{r['src']:5s} A={a_ol:2d} Ro={r_out:4d} Rtv={r_tv:7d}: gain {ref:+.1f} dB, "
                          f"HP {lo:.1f} Hz (board {lo_mb:.1f}), LP {hi/1000:.1f} kHz (board {hi_mb/1000:.1f})")
    if args.golden:
        ref = [r for r in results if r["src"] == "pulse" and r["a_ol"] == 20 and r["r_out"] == 1000 and r["r_tv"] == 47000][0]
        args.golden.mkdir(parents=True, exist_ok=True)
        (args.golden / "nes001_audio.json").write_text(json.dumps(ref, indent=2) + "\n")
        lines = ["/* Generated by tools/circuits/sweep_nes001_audio.py --golden: ngspice run of",
                 " * nes001_audio.cir, pulse pin, a_ol=20, r_out=1k, r_tv=47k. Do not edit. */",
                 "#ifndef NES001_AUDIO_GOLDEN_H", "#define NES001_AUDIO_GOLDEN_H",
                 f"#define NES001_AUDIO_GOLDEN_HP_HZ {ref['hp_hz']:.2f}f",
                 f"#define NES001_AUDIO_GOLDEN_LP_HZ {ref['lp_hz']:.1f}f",
                 "static const float nes001_audio_golden_hz[] = {" + ", ".join(f"{h}.0f" for h in TEST_HZ) + "};",
                 "static const float nes001_audio_golden_db[] = {" + ", ".join(f"{ref['response_db'][str(h)]:.3f}f" for h in TEST_HZ) + "};",
                 "#endif", ""]
        (args.golden / "nes001_audio.h").write_text("\n".join(lines))
    (args.output / "results.json").write_text(json.dumps({
        "model": "NES-001 motherboard mixer and 74HC04 gate amplifier (Schenk) plus the AV module follower and jack (EDC trace); "
                 "behavioural gate, assumed follower and shunt capacitors. Not calibrated.",
        "results": results}, indent=2) + "\n")


if __name__ == "__main__":
    main()
